version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80" # 호스트의 8080 포트를 컨테이너의 80번 포트로 매핑
    depends_on:
      - backend # 백엔드가 실행된 후 프론트엔드 실행
    volumes:
      - ./frontend:/usr/src/app
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    networks:
      - app-network

  database:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "teampassword"
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge