version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80" # 호스트의 8080 포트를 컨테이너의 80번 포트로 매핑
    depends_on:
      - backend # 백엔드가 실행된 후 프론트엔드 실행
    volumes:
      - ./frontend:/usr/src/app

  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    
    # docker에서 모든 환경변수를 백 env에서 가져와서 사용함 따로 지정안해도되니 매우 편리함
    # 근대 싹다 가져옴 (필요없는것도 다)
    # env_file:
    #   - ./backend/.env
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_CONNECTION_LIMIT: ${DB_CONNECTION_LIMIT}

  database:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "teampassword"
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

# 프론트엔드 : 리액트 앱을 엔진엑스로 서빙하며 엔진엑스 설정에 따라 /api/ 요청은 백엔드로 전달된다.
# 백엔드 : express 서버로 3001번 포트에서 실행된다.
# 디비 : MySQL 컨테이너는 3307번 포트에서 실행되며 데이터는 db_data 볼륨에 저장된다.